name: cookiecutter-analytical-project
channels:
    - defaults
    - conda-forge
dependencies:
    - pytest==8.2.1
    - pytest-cookies==0.7.0
    - setuptools==78.1.0
    - pre-commit==4.2.0
    - ruff==0.11.10
    - bandit[toml]==1.8.3