# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.5
    hooks:
    -   id: ruff
        args: [--fix]
    -   id: ruff-format
{% if cookiecutter.use_R == "yes" %}
-   repo: https://github.com/lorenzwalthert/precommit
    rev: v0.3.0
    hooks:
    -   id: style-files
    -   id: lintr
        args: [--warn_only]
        verbose: true
{%- endif -%}