name: {{ cookiecutter.repo_name }}
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - coverage
  - ruff
  - python-dotenv>=0.5.1
  - pre_commit
  - cookiecutter
  - questionary
  - pip
  - pip:
      - vulture==2.14