name: {{ cookiecutter.repo_name }}
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - coverage
  - black
  - python-dotenv>=0.5.1
  - pre_commit
  - pip:
    - BioLizardStylePython
  {% if cookiecutter.use_R == "yes" %}
  - r
  - r-essentials
  - rstudio
  - r-tidyverse
  - r-devtools  # Add devtools for installing from GitHub (via post_gen_project.py hook)
  {%- endif -%}
